### ISSUE TITLE
No Corona Editor Menu in Sublime 2

### ISSUE THREAD

**Issue by sheppe** [coronalabs/CoronaSDK-SublimeText#18]
I just upgraded to the most recent version via Package Control, and the Corona Editor menu is gone. Here's the console error:

snippets exception: [Errno 2] No such file or directory: 'Packages/Corona Editor/Main.sublime-menu.template'
Corona Editor: Failed to load Snippets menu: Packages/Corona Editor/Main.sublime-menu.template

I have verified that the file is indeed at that location within the Sublime 2 installation directory.

**Comment by perry-clarke** [comment]
This is fixed in Corona Editor 1.5.1
