### ISSUE TITLE
elseif auto-indent borked

### ISSUE THREAD

**Issue by perry-clarke** [coronalabs/CoronaSDK-SublimeText#19]
http://forums.coronalabs.com/topic/44079-indentation-issue/

Reproed in ST 3 and with "Corona SDK Lua" syntax set.

**Comment by landoncope** [comment]
See latest comment in https://forums.coronalabs.com/topic/44079-indentation-issue/ for possible solution

**Comment by perry-clarke** [comment]
This was fixed in 1.6.0
