### ISSUE TITLE
FYI: The new Corona rebranding breaks this plugin

### ISSUE THREAD

**Issue by poisa** [coronalabs/CoronaSDK-SublimeText#23]
It's a minor inconvenience that could be addressed with an addition to the docs really.

Basically the new rebranding now installs (in OSX) as `Corona-<version>` so you need to rename your install dir as `CoronaSDK` in order for the editor to work.

It would be awesome if the editor would have a preference that would allow you to launch a specific version of the SDK. I always keep many versions installed for testing but can only debug with the one that's named `CoronaSDK`.

**Comment by perry-clarke** [comment]
We'll fix the issue raised by the change in the install directory name but in the mean time you can use the `corona_sdk_simulator_path` preference documented [here](https://github.com/coronalabs/CoronaSDK-SublimeText#preferences) to specify the version of Corona you want to run.

**Comment by perry-clarke** [comment]
This is fixed in release 1.7.0
