### ISSUE TITLE
Run Project stopped working

### ISSUE THREAD

**Issue by renatosc** [coronalabs/CoronaSDK-SublimeText#25]
I am not able to call "Corona Editor - >Run Project" anymore (or CMD+B)   (OS X)

I keep getting an error popup with the message:
The document "main.lua" could not be opened. Corona Simulator cannot open files in the "Lua Source Code" format.

Is it only me?

**Comment by beernathan** [comment]
I'm having the same problem - can't run my project.

**Comment by renatosc** [comment]
I was able to pinpoint the problem:  Corona is not putting the path for the main.lua inside quotes,  so if you have any space inside your path you will get that error...

**Comment by renatosc** [comment]
I just made a pull request with the fix.

**Comment by perry-clarke** [comment]
Thanks for the reports (and the pull request).  Release 1.7.3 is available (quit and restart Sublime Text to get it) and it fixes the issue with spaces in drive names and filenames on macOS.
