### ISSUE TITLE
Go To Symbol not working correctly

### ISSUE THREAD

**Issue by renatosc** [coronalabs/CoronaSDK-SublimeText#27]
The Go To Symbol (CMD+R) shortcut is not properly working anymore when you define a function as following:

```
local getHello = function()
end
```
The Symbol appearing on the list is "function" instead of "getHello"

**Comment by personalnadir** [comment]
I have fixed this in my pull request #31

**Comment by personalnadir** [comment]
This should work correctly now

**Comment by personalnadir** [comment]
@Shchvova I think this one can be closed
