### ISSUE TITLE
Simulator of newest Solar2d build is not opening right on "run project"

### ISSUE THREAD

**Issue by DimaUndSo** [coronalabs/CoronaSDK-SublimeText#39]
With the newest Solar2d build (2020.3598) opening the simulator through sublime text 3 doesn't work on MacOs. 

The icon appears in the dock, but the simulator itself does not open.
<img width="58" alt="screenshot" src="https://user-images.githubusercontent.com/19418191/84440154-d121fb80-ac39-11ea-8332-11b92af695c7.png">

I tried to enter the path to the simulator manually in the Corona Editor.sublime-settings file, but that didn't help. Setting the path to another old Corona build (2018.3326) does work well. So the path seems not to be the reason for this issue.

I can open the simulator manually though, but not through sublime.

Maybe you guys can take a look into it some time. Appreciate it.
Thanks

**Comment by personalnadir** [comment]
This sounds like coronalabs/corona#79 as opposed to an issue with the Sublime plugin

**Comment by Shchvova** [comment]
Yes. It is. Closing this issue.
