### ISSUE TITLE
Corona SDK Debugger not working anymore (latest dev. build)

### ISSUE THREAD

**Issue by BioflakesDG** [coronalabs/CoronaSDK-SublimeText#40]
Using the latest Corona 2020.3583 build with SublimeText build 3211, the debugger does not work anymore and all the options (Run, Toggle Breakpoints etc.) in the dropdown are just greyed-out.

I've tested this with another earlier daily build and the same issues persisted - however with the latest build, using the normal Corona Editor, the Corona Editor tab doesn't even appear anymore. So I've tried switching from that to the latest one over at [https://github.com/coronalabs/CoronaSDK-SublimeText](url) but the debugger still only has greyed-out options.

Launching the application normally through SublimeText 3 works, however.

**Comment by personalnadir** [comment]
Are you getting errors in your Sublime console?

**Comment by BioflakesDG** [comment]
No errors or anything. I can run and build my apps just fine - everything works on that end. But the debugger is just greyed out and doesn't work anymore. Same on my friend's PC, where he tried various other builds as well.

**Comment by BioflakesDG** [comment]
Seems like it's been fixed with the latest update. Thank you.
